# Generated by Django 5.0.6 on 2024-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='patronymic')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('passport_number', models.CharField(max_length=11, unique=True, verbose_name='passport_number')),
                ('birth_place', models.CharField(max_length=300, verbose_name='birth_place')),
                ('phone', models.IntegerField(unique=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('registration_address', models.CharField(max_length=300)),
                ('residential_address', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
