# Generated by Django 5.0.6 on 2024-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='birth_place'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='passport_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='patronymic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='registration_address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residential_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='residential_address'),
        ),
    ]
