version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy